apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-dbsyncsh
data:
  db-sync.sh: |+
    #!/bin/bash
    set -ex

    keystone-manage db_sync
      kolla_keystone_bootstrap {{ .Values.global.keystone.admin_user }} {{ .Values.global.keystone.admin_password }} {{ .Values.global.keystone.admin_project_name }} admin http://keystone-api:{{ .Values.global.network.port.admin }}/v3 http://keystone-api:{{ .Values.global.network.port.public }}/v3 http://keystone-api:{{ .Values.global.network.port.public }}/v3 {{ .Values.global.keystone.admin_region_name }}
