apiVersion: v1
kind: Service
metadata:
  name: glance-api
spec:
  ports:
  - name: glance-api-public
    port: {{ .Values.global.network.port.api}}
  #- name: keystone-api-admin
  #  port: {{ .Values.global.network.port.admin }}
  selector:
    app: glance-api
