apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-startsh
data:
  start.sh: |+
    #!/bin/bash
    set -ex

    # Loading Apache2 ENV variables
    source /etc/apache2/envvars
    rm -rf /var/run/apache2/*
    APACHE_DIR="apache2"

    apache2 -DFOREGROUND
